### ISSUE TITLE
Long is returned instead of int

### ISSUE THREAD

**Issue by TheElectronWill** [TheElectronWill/TOML-javalib#3]
A toml file like this:

``` toml
integer = 25565
long = 12345678900
```

gives two long values. But the first one should be an int!
